import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn}from'node:child_process';
import server from '../bridge/server.cjs';import {Codex}from'../app/codex.cjs';import {Integrations}from'../app/integrations.cjs';
const event={hook_event_name:'PermissionRequest',session_id:'test-session',cwd:'C:/fixture',tool_name:'Bash',tool_input:{command:'echo fixture'}};
function relay(dir,payload){return new Promise((resolve,reject)=>{const p=spawn(process.execPath,['bridge/relay.cjs'],{env:{...process.env,ORBIT_DATA_DIR:dir},windowsHide:true});let out='';p.stdout.on('data',b=>out+=b);p.on('error',reject);p.on('exit',()=>resolve(JSON.parse(out)));p.stdin.end(JSON.stringify(payload))})}
test('permission relay returns only authenticated user decision; oversized details remain observational',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orbit-permission-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let calls=0;const s=await server.startServer(dir,()=>{},{onPermission:async e=>{calls++;assert.equal(e.tool_input.command,'echo fixture');return'allow'}});try{assert.deepEqual(await relay(dir,event),{hookSpecificOutput:{hookEventName:'PermissionRequest',decision:{behavior:'allow'}}});assert.deepEqual(await relay(dir,{...event,tool_input:{command:'x'.repeat(6000)}}),{});assert.equal(calls,1)}finally{await s.close()}});
test('closing approval server releases Codex without authorizing',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orbit-disconnect-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let ready;const waiting=new Promise(r=>ready=r);const s=await server.startServer(dir,()=>{},{onPermission:()=>{ready();return new Promise(()=>{})}});const result=relay(dir,event);await waiting;await s.close();assert.deepEqual(await result,{})});
test('app-server approval is single-use, correlated and constrained by available decisions',()=>{const messages=[],events=[];const c=new Codex({emit:(n,p)=>events.push([n,p])});c.write=m=>messages.push(m);c.thread={id:'thread'};c.active={turnId:'turn'};c.receive({id:4,method:'item/commandExecution/requestApproval',params:{threadId:'thread',turnId:'turn',itemId:'item',command:'echo safe',availableDecisions:['decline']}});const card=events.find(e=>e[0]==='approval')[1];assert.equal(card.canAllow,false);assert.throws(()=>c.decide(card.requestId,'allow'));c.decide(card.requestId,'deny');assert.deepEqual(messages.at(-1),{id:4,result:{decision:'decline'}});assert.throws(()=>c.decide(card.requestId,'deny'))});
test('app-server streaming filters foreign threads and final text overrides deltas',()=>{let reply;const c=new Codex();c.thread={id:'owned'};c.active={messages:new Map(),resolve:r=>reply=r,reject:()=>{}};c.receive({method:'item/agentMessage/delta',params:{threadId:'foreign',itemId:'x',delta:'secret'}});c.receive({method:'item/agentMessage/delta',params:{threadId:'owned',itemId:'a',delta:'partial'}});c.receive({method:'item/completed',params:{threadId:'owned',item:{id:'a',type:'agentMessage',text:'final'}}});c.receive({method:'turn/completed',params:{threadId:'owned',turn:{status:'completed'}}});assert.equal(reply.text,'final')});
test('all integration adapters are bounded read-only requests and disabled adapters make no calls',async()=>{const calls=[],events=[];let enabled=false;const i=new Integrations({secret:k=>k==='n8n-url'?'https://fixture.example':'fixture-token',enabled:()=>enabled,emit:(n,e)=>events.push(e),fetchImpl:async(url,opts)=>{calls.push([String(url),opts]);assert.equal(opts.redirect,'error');assert.ok(!opts.method||opts.method==='POST'&&String(url)==='https://api.notion.com/v1/search');const data=String(url).includes('/user/repos')?[]:String(url).includes('executions')?{data:[{id:'1',workflowId:'2',status:'success'}]}:{available:[{amount:50,currency:'brl'}],data:[],results:[],deployments:[],name:'Workflow'};return new Response(JSON.stringify(data),{headers:{'content-type':'application/json'}})}});for(const id of ['stripe','github','vercel','n8n','resend','notion','calcom'])await i.refresh('integration_'+id);assert.equal(calls.length,0);enabled=true;for(const id of ['stripe','github','vercel','n8n','resend','notion','calcom'])await i.refresh('integration_'+id);assert.equal(events.length,7);assert.ok(events.every(e=>e.error===null));i.close()});
