const {app,BrowserWindow,ipcMain,screen,Tray,Menu,nativeImage,shell,session,dialog,safeStorage}=require('electron');
const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const {randomUUID,createHash}=require('node:crypto');const {findNode}=require('./node-runtime.cjs');
const {startServer}=require('../bridge/server.cjs');const {storageDir}=require('../bridge/protocol.cjs');const installer=require('../bridge/install.cjs');const {Sessions}=require('./sessions.cjs');const {Codex}=require('./codex.cjs');const pkg=require('../package.json');
const dir=storageDir();app.setPath('userData',path.join(dir,'desktop'));
const sessions=new Sessions(),grants=new Map(),attachments=new Map();
let win,settingsWin,tray,server,nodePath,pendingPlan,pendingFingerprint,paused=false,collapsed=false,rect={x:240,y:0,width:240,height:6},mouseThrough=null;
const defaults={soundEnabled:true,soundVolume:.12,autoCloseInterval:15,absenceInterval:180,activeIntegrations:['integration_resend','integration_n8n','integration_vercel','integration_github'],screen:'primary',autostart:false,hooksInstalled:false,model:''};
let settings={...defaults},project=path.join(dir,'workspace');
function emit(name,payload){for(const w of [win,settingsWin])if(w&&!w.isDestroyed())w.webContents.send('orbit:event:'+name,payload)}
const hookApprovals=new Map();
function hookPermission(event,signal){
 if(paused||!win||win.isDestroyed()||win.webContents.isLoading()||hookApprovals.size>=4)return null;
 const requestId='hook:'+randomUUID();
 return new Promise(resolve=>{let finished=false;let timer;const done=decision=>{if(finished)return;finished=true;clearTimeout(timer);hookApprovals.delete(requestId);emit('approval-resolved',{requestId});resolve(decision)};timer=setTimeout(()=>done(null),700);done.ack=()=>{if(finished||done.acked)return;done.acked=true;clearTimeout(timer);timer=setTimeout(()=>done(null),90000)};hookApprovals.set(requestId,done);signal.addEventListener('abort',()=>done(null),{once:true});emit('approval',{requestId,sessionId:event.session_id,tool:event.tool_name,command:event.cwd+'\n'+JSON.stringify(event.tool_input,null,2),canAllow:true,source:'VS Code'});});
}
const codex=new Codex({emit});
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}}
function writeJson(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.'+randomUUID()+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2),{mode:0o600});fs.renameSync(tmp,file)}
function display(){return settings.screen==='cursor'?screen.getDisplayNearestPoint(screen.getCursorScreenPoint()):screen.getPrimaryDisplay()}
function position(){if(!win)return;const b=display().bounds;win.setBounds({x:Math.round(b.x+(b.width-720)/2),y:b.y,width:720,height:collapsed?6:320});emit('screen-changed',null)}
function hitTest(){if(!win||win.isDestroyed())return;const p=screen.getCursorScreenPoint(),b=win.getBounds(),x=p.x-b.x,y=p.y-b.y;const r=collapsed?{x:240,y:0,width:240,height:6}:rect;const through=!(x>=r.x-3&&x<=r.x+r.width+3&&y>=r.y&&y<=r.y+r.height+3);if(through!==mouseThrough){mouseThrough=through;win.setIgnoreMouseEvents(through,{forward:true})}emit('cursor',{x,y})}
function secureWindow(options,file){const w=new BrowserWindow({...options,icon:path.join(__dirname,'../assets/icon.png'),webPreferences:{preload:path.join(__dirname,'preload-island.cjs'),contextIsolation:true,sandbox:true,nodeIntegration:false,devTools:!app.isPackaged}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',e=>e.preventDefault());void w.loadFile(path.join(__dirname,'../dist',file));return w}
function trusted(e){if(![win,settingsWin].some(w=>w&&!w.isDestroyed()&&e.sender===w.webContents&&e.senderFrame===w.webContents.mainFrame))throw new Error('Invalid sender')}
function text(v,max=10000){if(typeof v!=='string'||v.length>max)throw new Error('Invalid text');return v}
function bool(v){if(typeof v!=='boolean')throw new Error('Invalid boolean');return v}
function hooksStatus(){if(!nodePath)nodePath=findNode();const p=nodePath?installer.preview({nodePath,dir}):null;return{installed:!!p?.installed,settingsPath:p?.file||path.join(process.env.CODEX_HOME||path.join(os.homedir(),'.codex'),'hooks.json'),hookPath:path.join(dir,'bridge','relay.cjs'),hookReady:!!nodePath}}
const secretKeys=new Set(['stripe-api-key','github-token','vercel-token','n8n-url','n8n-api-key','resend-api-key','notion-api-key','calcom-api-key']);
function secret(key,value){if(!secretKeys.has(key))throw new Error('Invalid key');const file=path.join(dir,'secrets.json'),data=readJson(file,{});if(value===undefined){return data[key]?safeStorage.decryptString(Buffer.from(data[key],'base64')):null}if(value){if(!safeStorage.isEncryptionAvailable())throw new Error('Armazenamento protegido do Windows indisponível.');data[key]=safeStorage.encryptString(text(value)).toString('base64')}else delete data[key];writeJson(file,data)}
let integrations;
function grantFile(file){const stat=fs.statSync(file);if(!stat.isFile()||stat.size>10*1024*1024)throw new Error('Selecione um arquivo de até 10 MB.');if(grants.size>=20)grants.delete(grants.keys().next().value);const id=randomUUID();grants.set(id,{file,expires:Date.now()+300000});return id}
function ingest(id){if(attachments.has(id))return attachments.get(id).info;const grant=grants.get(id);if(!grant||grant.expires<Date.now())throw new Error('Selecione o arquivo novamente.');const stat=fs.statSync(grant.file);if(!stat.isFile()||stat.size>10*1024*1024)throw new Error('Arquivo inválido ou maior que 10 MB.');if([...attachments.values()].reduce((n,a)=>n+a.info.size,0)+stat.size>30*1024*1024)throw new Error('Limite de anexos: 30 MB.');const inbox=path.join(dir,'inbox');fs.mkdirSync(inbox,{recursive:true});const copy=path.join(inbox,randomUUID()+path.extname(grant.file));fs.copyFileSync(grant.file,copy,fs.constants.COPYFILE_EXCL);const info={path:id,name:path.basename(grant.file),size:stat.size};attachments.set(id,{info,file:copy});grants.delete(id);return info}
async function fileInput(context){if(!context)return[];if(context.kind!=='file')throw new Error('Selecione um arquivo para dar contexto.');const a=attachments.get(context.path);if(!a)throw new Error('Anexo não preparado.');const ext=path.extname(a.file).toLowerCase();if(ext==='.pdf'){if(!a.pdf)a.pdf=await require('./pdf.cjs').readPdf(a.file,path.dirname(a.file));return [{type:'text',text:'PDF anexado: '+a.info.name+'\n'+a.pdf.text},...a.pdf.files.map(file=>({type:'localImage',path:file}))]}if(['.png','.jpg','.jpeg','.webp','.gif'].includes(ext))return[{type:'localImage',path:a.file}];if(a.info.size>512*1024)throw new Error('Contexto textual limitado a 512 KB.');const bytes=fs.readFileSync(a.file);if(bytes.includes(0))throw new Error('Formato binário não suportado como texto. Use uma imagem ou exporte o documento para texto.');return[{type:'text',text:'Arquivo anexado pelo usuário: '+a.info.name+'\n<attachment>\n'+bytes.toString('utf8')+'\n</attachment>'}]}
function cleanupOldInbox(){const inbox=path.join(dir,'inbox');if(!fs.existsSync(inbox)||fs.lstatSync(inbox).isSymbolicLink())return;for(const name of fs.readdirSync(inbox)){const file=path.join(inbox,name);const stat=fs.lstatSync(file);if(stat.isSymbolicLink())continue;if(stat.isDirectory()&&/^pdf-[a-zA-Z0-9]+$/.test(name)){try{require('./pdf.cjs').cleanup(file)}catch{}}else if(stat.isFile()&&/^[a-f0-9-]{36}\.[a-zA-Z0-9]+$/.test(name)){fs.unlinkSync(file)}}}
function cleanupAttachments(){for(const a of attachments.values()){try{fs.unlinkSync(a.file)}catch{}if(a.pdf?.folder)try{require('./pdf.cjs').cleanup(a.pdf.folder)}catch{}}attachments.clear();grants.clear()}
async function openUrl(raw){const u=new URL(text(raw,4096));if(u.protocol!=='https:'||u.username||u.password)throw new Error('Somente links HTTPS.');const allowed=['github.com','vercel.com','vercel.app','resend.com','notion.so','www.notion.so','cal.com','app.cal.com','dashboard.stripe.com','docs.github.com','developers.openai.com'];const configured=secret('n8n-url');if(!allowed.some(h=>u.hostname===h||u.hostname.endsWith('.'+h))&&(!configured||u.origin!==new URL(configured).origin))throw new Error('Destino não configurado.');await shell.openExternal(u.href)}
const commands={
 boot:()=>({settings:{...settings,hooksInstalled:hooksStatus().installed},version:pkg.version,screen:{...display().bounds,scale:display().scaleFactor},hookPath:hooksStatus().hookPath}),
 save_settings:({settings:s})=>{const next={soundEnabled:bool(s.soundEnabled),soundVolume:Math.max(0,Math.min(.2,Number(s.soundVolume)||0)),autoCloseInterval:Math.max(5,Math.min(120,Number(s.autoCloseInterval)||15)),absenceInterval:Math.max(30,Math.min(3600,Number(s.absenceInterval)||180)),activeIntegrations:s.activeIntegrations.filter(x=>/^integration_(resend|n8n|vercel|github|notion|calcom|stripe)$/.test(x)).slice(0,4),screen:s.screen==='cursor'?'cursor':'primary',autostart:bool(s.autostart),hooksInstalled:hooksStatus().installed,model:text(s.model,128)};if(next.autostart!==settings.autostart)app.setLoginItemSettings({openAtLogin:next.autostart});settings=next;integrations?.cancel();writeJson(path.join(dir,'settings.json'),settings);position();emit('settings-changed',settings)},
 set_collapsed:({collapsed:v})=>{if(collapsed===v)return;collapsed=bool(v);position()},
 set_island_rect:a=>{for(const k of ['x','y','width','height'])if(!Number.isFinite(a[k]))throw new Error('Invalid rectangle');rect={x:Math.max(0,Math.min(720,a.x)),y:Math.max(0,Math.min(320,a.y)),width:Math.max(0,Math.min(720,a.width)),height:Math.max(0,Math.min(320,a.height))};hitTest()},
 focus_window:({focused})=>{win.setFocusable(bool(focused));if(focused)win.focus();else win.blur()},
 reposition:()=>{const b=display().bounds;win.setPosition(Math.round(b.x+(b.width-720)/2),b.y)},
 open_url:({url})=>openUrl(url),open_in_vscode:async()=>{await shell.openExternal('vscode://');return true},quit_app:()=>app.quit(),
 open_settings_window:()=>{if(settingsWin&&!settingsWin.isDestroyed()){settingsWin.focus();return}settingsWin=secureWindow({title:'Orbit — Preferências',width:760,height:780,backgroundColor:'#15161a',autoHideMenuBar:true},'settings.html')},
 log_line:()=>{},hooks_status:hooksStatus,
 hooks_preview:({install})=>{if(!nodePath)throw new Error('Instale Node.js 22+.');pendingPlan=installer.preview({install:bool(install),nodePath,dir});pendingFingerprint=createHash('sha256').update(JSON.stringify(pendingPlan)).digest('hex');return{diff:'Antes:\n'+pendingPlan.before+'\n\nDepois:\n'+pendingPlan.after,backup:'Backup automático antes de salvar',settingsPath:pendingPlan.file,fingerprint:pendingFingerprint}},
 hooks_apply:({install,fingerprint})=>{if(!pendingPlan||fingerprint!==pendingFingerprint||install!==pendingPlan.install)throw new Error('Revise a prévia novamente.');const r=installer.apply(pendingPlan,path.join(__dirname,'../bridge'));pendingPlan=null;return JSON.stringify(r)},
 approval_decision:({requestId,decision})=>hookApprovals.has(requestId)?hookApprovals.get(requestId)(['allow','deny'].includes(decision)?decision:null):codex.decide(requestId,decision),approval_ack:({requestId})=>hookApprovals.get(requestId)?.ack(),approval_decline:({requestId})=>{if(hookApprovals.has(requestId))hookApprovals.get(requestId)(null);else if(codex.approvals.has(requestId))codex.decide(requestId,'deny')},
 chat_send:async({query,context})=>codex.send({query,cwd:project,model:settings.model,input:await fileInput(context)}),chat_cancel:()=>codex.cancel(),chat_reset:async()=>{await codex.reset();cleanupAttachments()},chat_answer:({requestId,answers})=>codex.answer(requestId,answers),models:()=>codex.models(),
 ingest_file:({path:id})=>ingest(id),choose_file:async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile']});return r.canceled?null:ingest(grantFile(r.filePaths[0]))},
 choose_project:async()=>{if(codex.active)throw new Error('Interrompa o turno atual antes de mudar de projeto.');const r=await dialog.showOpenDialog(settingsWin||win,{properties:['openDirectory']});if(r.canceled)return null;await codex.reset();project=r.filePaths[0];writeJson(path.join(dir,'project.json'),{project});return project},
 secret_present:({key})=>!!secret(key),secret_set:({key,value})=>{if(key==='n8n-url'&&value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw new Error('Use URL HTTPS sem credenciais.')}secret(key,value);emit('settings-changed',settings)},secret_clear:({key})=>secret(key,''),
 refresh_integration:({id})=>integrations.refresh(id),open_n8n:()=>{const url=secret('n8n-url');if(url)return openUrl(url)},set_paused:({paused:v})=>{paused=bool(v);if(paused)for(const done of hookApprovals.values())done(null);integrations?.cancel()},
};
if(!app.requestSingleInstanceLock())app.quit();else{
 app.on('second-instance',()=>{win?.showInactive();emit('tray','open')});
 app.whenReady().then(async()=>{
  fs.mkdirSync(project,{recursive:true});cleanupOldInbox();settings={...defaults,...readJson(path.join(dir,'settings.json'),{})};const saved=readJson(path.join(dir,'project.json'),{});if(saved.project&&fs.existsSync(saved.project))project=saved.project;
  if(process.windowsStore)require('./store-paths.cjs').validateStorePaths({home:os.homedir(),localAppData:process.env.LOCALAPPDATA,roamingAppData:process.env.APPDATA,codexHome:process.env.CODEX_HOME||path.join(os.homedir(),'.codex'),dir});
  session.defaultSession.setPermissionRequestHandler((_w,_p,cb)=>cb(false));session.defaultSession.setPermissionCheckHandler(()=>false);
  nodePath=findNode();
  win=secureWindow({title:'Orbit for Codex',width:720,height:320,frame:false,transparent:true,alwaysOnTop:true,skipTaskbar:true,resizable:false,show:false,focusable:false},'index.html');
  ipcMain.handle('orbit:invoke',(e,command,args={})=>{trusted(e);if(!Object.hasOwn(commands,command))throw new Error('Invalid command');return commands[command](args||{})});
  ipcMain.handle('orbit:drop',(e,paths)=>{trusted(e);if(!Array.isArray(paths)||paths.length>1)throw new Error('Invalid drop');return paths.map(p=>grantFile(text(p,4096)))});
  win.showInactive();
  server=await startServer(dir,event=>{if(paused)return;if(sessions.accept(event)){emit('sessions',sessions.snapshot());emit('hook',{...event,cwd:event.project})}},{onPermission:hookPermission});
  const {Integrations}=require('./integrations.cjs');integrations=new Integrations({secret,emit,enabled:id=>!paused&&settings.activeIntegrations.includes(id)});integrations.start();
  tray=new Tray(nativeImage.createFromPath(path.join(__dirname,'../assets/icon.png')).resize({width:24,height:24}));tray.setToolTip('Orbit for Codex');tray.setContextMenu(Menu.buildFromTemplate([{label:'Abrir Orbit',click:()=>emit('tray','open')},{label:'Preferências',click:()=>commands.open_settings_window()},{label:'Pausar / retomar',click:()=>emit('tray','pause')},{type:'separator'},{label:'Sair',click:()=>app.quit()}]));tray.on('click',()=>emit('tray','open'));
  position();win.once('ready-to-show',()=>win.showInactive());for(const name of ['display-metrics-changed','display-removed','display-added'])screen.on(name,position);setInterval(hitTest,32).unref();setInterval(()=>emit('sessions',sessions.snapshot()),10000).unref();
 }).catch(e=>{dialog.showErrorBox('Orbit for Codex',e.message);app.quit()});
 app.on('before-quit',()=>{for(const done of hookApprovals.values())done(null);codex.close();void require('./pdf.cjs').close();integrations?.close();void server?.close();cleanupAttachments();tray?.destroy()});app.on('window-all-closed',()=>app.quit());
}
