// Read-only provider adapters, derived from Coucou's MIT integration pollers.
const defs={stripe:['stripe-api-key',30],github:['github-token',300],vercel:['vercel-token',30],n8n:['n8n-api-key',15],resend:['resend-api-key',60],notion:['notion-api-key',300],calcom:['calcom-api-key',300]};
const str=v=>typeof v==='string'?v.slice(0,1000):'';
const list=v=>Array.isArray(v)?v:[];
class Integrations{
 constructor({secret,emit,enabled,fetchImpl=fetch}){this.secret=secret;this.emit=emit;this.enabled=enabled;this.fetch=fetchImpl;this.controllers=new Map();this.timers=[];this.last=new Map()}
 start(){for(const [provider,[,interval]]of Object.entries(defs)){const id='integration_'+provider;this.timers.push(setTimeout(()=>void this.refresh(id),3000));this.timers.push(setInterval(()=>void this.refresh(id),interval*1000))}}
 cancel(){for(const c of this.controllers.values())c.abort();this.controllers.clear()}
 close(){this.cancel();for(const t of this.timers){clearInterval(t);clearTimeout(t)}}
 async refresh(id){const provider=id.replace(/^integration_/,'');if(!defs[provider]||!this.enabled(id)||this.controllers.has(id))return;const key=this.secret(defs[provider][0]);if(!key)return;
  const controller=new AbortController();this.controllers.set(id,controller);const timer=setTimeout(()=>controller.abort(),10000);
  const request=async(url,options={})=>{const res=await this.fetch(url,{redirect:'error',...options,headers:{authorization:'Bearer '+key,'user-agent':'Orbit-for-Codex',...options.headers},signal:controller.signal});if(!res.ok)throw new Error('HTTP '+res.status);const reader=res.body.getReader();let chunks=[],size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>2*1024*1024){await reader.cancel();throw new Error('Resposta excedeu 2 MB.')}chunks.push(value)}return JSON.parse(Buffer.concat(chunks).toString('utf8'))};
  try{let data={},newest=null,event=null;
   if(provider==='stripe'){const balance=await request('https://api.stripe.com/v1/balance');const charges=await request('https://api.stripe.com/v1/charges?limit=3');const b=list(balance.available)[0]||{};const payments=list(charges.data).map(c=>({id:c.id,amount:c.amount,currency:c.currency,description:str(c.description||c.billing_details?.name),createdAt:c.created*1000,status:c.status}));data={balance:b.amount||0,currency:b.currency||'',payments};newest=payments[0]?.id;event={success:payments[0]?.status==='succeeded',label:'Pagamento atualizado',detail:payments[0]?.description||null}}
   if(provider==='github'){const user=await request('https://api.github.com/user');let stars=0;for(let page=1;page<=20;page++){const repos=await request('https://api.github.com/user/repos?per_page=100&affiliation=owner&sort=pushed&page='+page);for(const repo of list(repos))stars+=Number(repo.stargazers_count)||0;if(list(repos).length<100)break}data={totalRepos:(user.public_repos||0)+(user.owned_private_repos||0),totalStars:stars}}
   if(provider==='vercel'){const json=await request('https://api.vercel.com/v6/deployments?limit=5');const deployments=list(json.deployments).map(d=>({id:d.uid,projectName:str(d.name),state:d.state||d.readyState,url:str(d.url),createdAt:d.created||d.createdAt,commitMessage:str(d.meta?.githubCommitMessage||d.meta?.gitlabCommitMessage),branch:str(d.meta?.githubCommitRef||d.meta?.gitlabCommitRef)}));data={deployments};newest=deployments[0]?deployments[0].id+':'+deployments[0].state:null;event={success:deployments[0]?.state==='READY',label:deployments[0]?.projectName||'Vercel',detail:deployments[0]?.state||null}}
   if(provider==='resend'){const json=await request('https://api.resend.com/emails?limit=100');const emails=list(json.data).map(e=>({id:e.id,to:list(e.to).map(str),subject:str(e.subject),createdAt:e.created_at,lastEvent:e.last_event}));data={emails:emails.slice(0,3),total:emails.length}}
   if(provider==='notion'){const json=await request('https://api.notion.com/v1/search',{method:'POST',headers:{'content-type':'application/json','notion-version':'2022-06-28'},body:JSON.stringify({page_size:10,sort:{direction:'descending',timestamp:'last_edited_time'}})});data={pages:list(json.results).map(p=>{const title=p.title||Object.values(p.properties||{}).find(v=>v.type==='title')?.title;return{id:p.id,title:list(title).map(t=>str(t.plain_text||t.text?.content)).join('')||'Sem título',emoji:p.icon?.type==='emoji'?p.icon.emoji:null,lastEditedAt:p.last_edited_time,url:p.url}})}}
   if(provider==='calcom'){const json=await request('https://api.cal.com/v2/bookings?status=upcoming',{headers:{'cal-api-version':'2024-08-13'}});data={bookings:list(json.data).slice(0,100).map(b=>({id:String(b.id),title:str(b.title),start:b.start||b.startTime,status:b.status,attendeeName:str(b.attendees?.[0]?.name),attendeeEmail:str(b.attendees?.[0]?.email),attendeeNotes:str(b.responses?.notes?.value||b.description)}))}}
   if(provider==='n8n'){const base=this.secret('n8n-url');if(!base)return;const origin=new URL(base);if(origin.protocol!=='https:'||origin.username||origin.password)throw new Error('URL n8n inválida.');const endpoint=new URL(origin.href.replace(/\/$/,'')+'/api/v1/executions?limit=1&includeData=false');const json=await request(endpoint.href,{headers:{authorization:'','X-N8N-API-KEY':key}});const e=list(json.data)[0];if(e){let workflow='Workflow '+str(e.workflowId);if(e.workflowId){const w=await request(new URL(origin.href.replace(/\/$/,'')+'/api/v1/workflows/'+encodeURIComponent(e.workflowId)).href,{headers:{authorization:'','X-N8N-API-KEY':key}});workflow=str(w.name)||workflow}data={workflow,status:e.status};newest=e.id+':'+e.status;event={success:e.status==='success',label:workflow,detail:e.status}}}
   if(!controller.signal.aborted&&this.enabled(id)){const changed=newest&&this.last.has(id)&&this.last.get(id)!==newest;if(newest)this.last.set(id,newest);this.emit('integration',{id,data,error:null,event:changed?event:null})}
  }catch(e){if(!controller.signal.aborted)this.emit('integration',{id,data:{},error:e.message.startsWith('HTTP ')?e.message:'Falha ao consultar serviço.',event:null})}
  finally{clearTimeout(timer);this.controllers.delete(id)}
 }
}
module.exports={Integrations};
