import {_electron as electron}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import http from'node:http';import {spawn}from'node:child_process';
const root=process.cwd(),base=path.resolve('.test-output','island-'+Date.now()),home=path.join(base,'codex'),dir=path.join(base,'data');fs.mkdirSync(home,{recursive:true});let calls=0,received='';
const fixture=http.createServer((req,res)=>{let body='';req.on('data',c=>body+=c);req.on('end',()=>{received=body;calls++;const item={id:'msg_'+calls,type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'Resposta de teste: conversa recebida pelo Codex.',annotations:[]}]};const response={id:'resp_'+calls,object:'response',status:'completed',output:[item],usage:{input_tokens:1,output_tokens:1,total_tokens:2}};res.writeHead(200,{'content-type':'text/event-stream'});const events=[{type:'response.created',response:{...response,status:'in_progress',output:[]}},{type:'response.output_item.added',output_index:0,item:{...item,status:'in_progress',content:[]}},{type:'response.output_text.delta',item_id:item.id,output_index:0,content_index:0,delta:item.content[0].text},{type:'response.output_item.done',output_index:0,item},{type:'response.completed',response}];for(const e of events)res.write(`event: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`);res.end()})});await new Promise(r=>fixture.listen(0,'127.0.0.1',r));
fs.writeFileSync(path.join(home,'config.toml'),`model_provider="fixture"\nmodel="fixture"\nsandbox_mode="read-only"\n[features]\nplugins=false\nremote_plugin=false\napps=false\n[model_providers.fixture]\nname="Local fixture"\nbase_url="http://127.0.0.1:${fixture.address().port}/v1"\nwire_api="responses"\nrequires_openai_auth=false\n`);
const env={...process.env,ORBIT_DATA_DIR:dir,CODEX_HOME:home};for(const k of ['ELECTRON_RUN_AS_NODE','OPENAI_API_KEY','CODEX_API_KEY','OPENAI_BASE_URL'])delete env[k];
const app=await electron.launch({args:[process.env.ORBIT_TEST_APP||root],env,executablePath:process.env.ORBIT_TEST_EXE});
const testProcess=app.process();
try{
 const page=await app.firstWindow(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.locator('#island').waitFor();
 const show=async()=>{await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.send('orbit:event:tray','open'));await page.waitForTimeout(500)};
 await page.waitForTimeout(3000);await show();assert.equal(await page.evaluate(()=>typeof window.require),'undefined');
 const size=await page.locator('#island').boundingBox();assert.ok(size.width>=630&&size.height<180,JSON.stringify(size));await page.locator('#island').screenshot({path:path.join(base,'overview.png')});
 await page.getByTitle('Ask',{exact:true}).click();await page.getByRole('textbox',{name:'Mensagem para o Codex'}).fill('Olá, teste local.');await page.getByRole('button',{name:'Enviar',exact:true}).click();await page.locator('.reply').filter({hasText:'Resposta de teste:'}).waitFor({timeout:30000});assert.equal(calls,1);await page.locator('#island').screenshot({path:path.join(base,'chat.png')});
 await page.getByRole('textbox',{name:'Mensagem para o Codex'}).fill('Continue');await page.getByRole('button',{name:'Enviar',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.reply').length===2 && !document.querySelector('.chat-input').disabled);assert.equal(calls,2);
 const file=path.join(base,'context.txt');fs.writeFileSync(file,'ORBIT_ATTACHMENT_FIXTURE');await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},file);await page.getByRole('button',{name:'Anexar arquivo',exact:true}).click();await page.locator('.chip').filter({hasText:'context.txt'}).waitFor();await page.getByRole('textbox',{name:'Mensagem para o Codex'}).fill('Leia o arquivo');await page.getByRole('button',{name:'Enviar',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.reply').length===3 && !document.querySelector('.chat-input').disabled);assert.ok(received.includes('ORBIT_ATTACHMENT_FIXTURE'));
 // Generate a real PDF with Chromium and pass it through the PDF worker.
 const pdf=path.join(base,'context.pdf');const pdfBytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.printToPDF({})).toString('base64'));fs.writeFileSync(pdf,Buffer.from(pdfBytes,'base64'));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},pdf);await page.getByRole('button',{name:'Anexar arquivo',exact:true}).click();await page.locator('.chip').filter({hasText:'context.pdf'}).waitFor();await page.getByRole('textbox',{name:'Mensagem para o Codex'}).fill('Leia o PDF');await page.getByRole('button',{name:'Enviar',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.reply').length===4 && !document.querySelector('.chat-input').disabled,{},{timeout:30000});assert.ok(received.includes('PDF anexado'),await page.locator('.reply').last().innerText());
 const prefPromise=app.waitForEvent('window');await page.evaluate(()=>window.orbit.invoke('open_settings_window'));const preferences=await prefPromise;await preferences.getByRole('heading',{name:'Chat Codex'}).waitFor();await preferences.screenshot({path:path.join(base,'settings.png')});await preferences.getByRole('button',{name:'Install hooks…',exact:true}).click();await preferences.getByRole('button',{name:'Back up and write',exact:true}).click();await preferences.waitForTimeout(400);assert.ok(fs.existsSync(path.join(home,'hooks.json')));await preferences.close();
 function hook(name,id='session-a',input={}){return new Promise((resolve,reject)=>{const p=spawn(process.execPath,[path.join(dir,'bridge','relay.cjs')],{env,windowsHide:true});let output='';p.stdout.on('data',b=>output+=b);p.on('error',reject);p.on('exit',()=>resolve(JSON.parse(output)));p.stdin.end(JSON.stringify({hook_event_name:name,session_id:id,cwd:'C:/demo/Projeto exemplo',tool_name:'Bash',...input}))})}
 await hook('UserPromptSubmit');await hook('PreToolUse','session-b');await show();await page.locator('#island').screenshot({path:path.join(base,'sessions.png')});
 const approval=hook('PermissionRequest','session-a',{tool_input:{command:'echo "aprovação de teste"'}});await page.getByRole('button',{name:'Allow',exact:false}).waitFor();await page.locator('#island').screenshot({path:path.join(base,'approval.png')});await page.getByRole('button',{name:'Allow',exact:false}).click();assert.equal((await approval).hookSpecificOutput.decision.behavior,'allow');
 await show();await page.keyboard.press('Escape');await page.waitForTimeout(500);const compact=await page.locator('#island').boundingBox();assert.ok(compact.height<=33&&compact.width<=290,JSON.stringify(compact));await page.locator('#island').screenshot({path:path.join(base,'compact.png')});
 assert.deepEqual(errors,[]);console.log('PASS: horizontal island, two chat turns, text/PDF attachments, settings, hook install, parallel sessions, real authenticated approval click, collapse. Screenshots: '+base);
}catch(e){console.error(e);throw e}finally{fixture.closeAllConnections();await new Promise(r=>fixture.close(r));await Promise.race([app.close(),new Promise(r=>setTimeout(r,7000))]);if(testProcess.exitCode===null)testProcess.kill()}
